# sanic from github on python:slim
# docker build -t ouds/sanic:0.1

FROM python:slim
MAINTAINER budshome.com <2558256956@qq.com>
RUN apt -y update 
# RUN apt install -y python3
# RUN apt install -y python3-pip
RUN pip install -U pip wheel setuptools
RUN pip install git+https://github.com/channelcat/sanic