FROM python
MAINTAINER budshome.com <2558256956@qq.com>
RUN apt -y update 
# RUN apt install -y python3
# RUN apt install -y python3-pip
RUN apt install -y python3-dev libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev
RUN pip install -U scrapy pip wheel setuptools